runtime: python39
entrypoint: gunicorn -b :$PORT scoring_system:app

# Instance class configuration
instance_class: B8  # Upgraded from B4 to B8

basic_scaling:
  max_instances: 5  # Adjust based on your needs
  idle_timeout: 10m  # Instances are terminated if idle for this period

env_variables:
  FLASK_ENV: 'production'

